version: '3.9'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: webpagegenie-db
    environment:
      - POSTGRES_DB=webpagegenie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
